### ISSUE TITLE
WeatherApp :- ReactJS

### ISSUE THREAD

**Issue by SohamRoy-01** [gauravghai/weatherApp-Reactjs#5]
## Hi @gauravghai I can't run the app after install all package and after downgrade my node -v
1. I change the API key.
2. ## ss:-
![Screenshot (7)](https://user-images.githubusercontent.com/104237973/219109231-44fe6e13-d0d5-41cd-89b0-56847e367223.png)
## Its keeps loading after allowing the permission
![Screenshot (8)](https://user-images.githubusercontent.com/104237973/219109423-8bf11221-901e-4e48-9da9-326dace5bfc6.png)

**Comment by gauravghai** [comment]
Hi, Make sure you have replace dummy API keys in apiKeys.JS file to your API keys from open weather site.

**Comment by SohamRoy-01** [comment]
Yeah I change the dummy keys with my keys in the url (openweathermap.org) of my account.

**Comment by SohamRoy-01** [comment]
Hi @gauravghai I don't know but its working right now..
Thank you for your time...
ss:-
![Screenshot (9)](https://user-images.githubusercontent.com/104237973/219118005-db14c3b9-29ab-4606-b278-4bcd735c00d1.png)
